import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Heroe from '../components/Heroe'
import Navbar from '../components/Navbar'
import Testmons from '../components/Testmons'

import styles from '../styles/pages/index.module.css'
import ali from '../public/images/avatar-ali.png'
import logo from '../public/images/logo.svg'

const Home: NextPage = () => {
  return (
    <div className={`${styles.home}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Heroe />
      
      <div className={`${styles.home__info}`}>
        <div className={`${styles['home__info-title']}`}>
          <h2>
            What’s different about Manage?
          </h2>

          <p>
            Manage provides all the functionality your team needs, without
            the complexity. Our software is tailor-made for modern digital
            product teams.
          </p>
        </div>


        <div className={`${styles.home__info__prod}`}>
          <div className={`${styles['home__info-prop']}`}>
            <div className={`${styles['home__info-prop-title']} flex flex-ai-c`}>
              <span>01</span> <h3>Track company-wide progress</h3>
            </div>
  
            <p>
              See how your day-to-day tasks fit into the wider vision. Go from
              tracking progress at the milestone level all the way done to the
              smallest of details. Never lose sight of the bigger picture again.
            </p>
          </div>

          <div className={`${styles['home__info-prop']}`}>
            <div className={`${styles['home__info-prop-title']} flex flex-ai-c`}>
              <span>02</span> <h3> Advanced built-in reports</h3>
            </div>
            <p>
            Set internal delivery estimates and track progress toward company
            goals. Our customisable dashboard helps you build out the reports
            you need to keep key stakeholders informed.
            </p>
          </div>

          <div className={`${styles['home__info-prop']}`}>
            <div className={`${styles['home__info-prop-title']} flex flex-ai-c`}>
              <span>03</span> <h3> Everything you need in one place</h3>
            </div>
            <p>
              Stop jumping from one service to another to communicate, store files,
              track tasks and share documents. Manage offers an all-in-one team
              productivity solution.
            </p>
          </div>
        </div>

      </div>


      <div className={`${styles.home__tests}`}>

        <h2>What they’ve said</h2>

        <Testmons />
        {/* <div className={`${styles['home__tests-peps']}`}>

          <div className='flex flex-ai-c flex-jc-c'>
            <div className={`${styles['home__tests-peps-img']} img`}>
              <Image src={ali} alt='' layout='fill'/>
            </div>
          </div>
          
          <h4>Anisha Li</h4>
          <p>
            “Manage has supercharged our team’s workflow. The ability to maintain
            visibility on larger milestones at all times keeps everyone motivated.”
          </p>
        </div> */}
{/* 
        Ali Bravo
        “We have been able to cancel so many other subscriptions since using
        Manage. There is no more cross-channel confusion and everyone is much
        more focused.”

        Richard Watts
        “Manage allows us to provide structure and process. It keeps us organized
        and focused. I can’t stop recommending them to everyone I talk to!”

        Shanai Gough
        “Their software allows us to track, manage and collaborate on our projects
        from anywhere. It keeps the whole team in-sync without being intrusive.” */}

        <div className={`${styles['home__tests-cta']}`}>
          <Link href='/'><a className='cta'>Get Started</a></Link>
        </div>
      </div>

      
      <div className={`${styles.home__footer}`}>
        <div className={`${styles['home__footer-cta']}`}>
          <div className={`${styles['home__footer-cta-wrapper']}`}>
            <div>
              <h2>Simplify how your team works today.</h2>
            </div>

            <div className={`${styles['']}`}>
              <Link href='/'><a className='cta white'>Get Started</a></Link>
            </div>
          </div>
        </div>


        <div className={`${styles['home__footer-links']}`}>
          <div className={`${styles['home__footer-links-wrapper']} container`}>

            <div className={`${styles['home__footer-links-form']}`}>
              <div>
                <input type="text" placeholder='updates in your inbox...'/>  
              </div>
              <div>
                <button>Go</button>
              </div>
            </div>



            <div className={`${styles['home__footer-links-sec']} flex flex-ai-c`}>
              <div className={`${styles['home__footer-links-sec-1']}`}>
                <Link href='/'><a>Home</a></Link>
                <Link href='/'><a>Pricing</a></Link>
                <Link href='/'><a>Products</a></Link>
                <Link href='/'><a>About Us</a></Link>
              </div>
              <div className={`${styles['home__footer-links-sec-2']}`}>
                <Link href='/'><a>Careers</a></Link>
                <Link href='/'><a>Community</a></Link>
                <Link href='/'><a>Privacy Policy</a></Link>
              </div>
            </div>

            <div className={`${styles['home__footer-links-icons']}`}>
              <div className={`${styles['home__footer-links-icons-logo']} img`}>
                <Image src={logo} alt='' layout='fill'/>
              </div>

              <div className={`${styles['home__footer-links-icons-socials']}`}>

              </div>
            </div>



          </div>
        </div> 
      </div>




    </div>
  )
      
}

export default Home
