import type { NextPage } from 'next'
import Head from 'next/head'
import Heroe from '../components/Heroe'
import Navbar from '../components/Navbar'

import styles from '../styles/pages/index.module.css'


const Home: NextPage = () => {
  return (
    <div className={`${styles.home}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Heroe />
      
      <div className={`${styles.home__info}`}>
        <div className={`${styles['home__info-title']}`}>
          <h2>
            What’s different about Manage?
          </h2>

          <p>
            Manage provides all the functionality your team needs, without
            the complexity. Our software is tailor-made for modern digital
            product teams.
          </p>
        </div>


        <div className={`${styles.home__info__prod}`}>
          <div className={`${styles['home__info-prop']}`}>
            <div className={`${styles['home__info-prop-title']} flex flex-ai-c`}>
              <span>01</span> <h3>Track company-wide progress</h3>
            </div>
  
            <p>
              See how your day-to-day tasks fit into the wider vision. Go from
              tracking progress at the milestone level all the way done to the
              smallest of details. Never lose sight of the bigger picture again.
            </p>
          </div>

          <div className={`${styles['home__info-prop']}`}>
            <div className={`${styles['home__info-prop-title']} flex flex-ai-c`}>
              <span>02</span> <h3> Advanced built-in reports</h3>
            </div>
            <p>
            Set internal delivery estimates and track progress toward company
            goals. Our customisable dashboard helps you build out the reports
            you need to keep key stakeholders informed.
            </p>
          </div>

          <div className={`${styles['home__info-prop']}`}>
            <div className={`${styles['home__info-prop-title']} flex flex-ai-c`}>
              <span>03</span> <h3> Everything you need in one place</h3>
            </div>
            <p>
              Stop jumping from one service to another to communicate, store files,
              track tasks and share documents. Manage offers an all-in-one team
              productivity solution.
            </p>
          </div>
        </div>

      </div>


      {/* What they’ve said

      Anisha Li
      “Manage has supercharged our team’s workflow. The ability to maintain
      visibility on larger milestones at all times keeps everyone motivated.”

      Ali Bravo
      “We have been able to cancel so many other subscriptions since using
      Manage. There is no more cross-channel confusion and everyone is much
      more focused.”

      Richard Watts
      “Manage allows us to provide structure and process. It keeps us organized
      and focused. I can’t stop recommending them to everyone I talk to!”

      Shanai Gough
      “Their software allows us to track, manage and collaborate on our projects
      from anywhere. It keeps the whole team in-sync without being intrusive.”

      Get Started

      Simplify how your team works today.
      Get Started

      Home
      Pricing
      Products
      About Us
      Careers
      Community
      Privacy Policy

      Updates in your inbox…
      Go */}





    </div>
  )
      
}

export default Home
